const places = [
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },
    {
        name: 'Caño Cristales River Trip',
        location: 'Bryce Canyon National Park, USA',
        price: 138,
        duration: 4,
        seat: 50,
        img: 'https://demo2.pavothemes.com/triply/wp-content/uploads/2020/11/5c48735739c52149617831f9_DSC04931-copy-1024x640.jpg',
        review: 4.1,
        video: '',
        description: 'Caño Cristales Tour, (aka the most beautiful river in the world) is an exceptional and surprising natural beauty. Its unique ecosystem is very fragile and now belongs to the Sierra de la Macarena Natural National Park.',
        Season: 'June - November',
    },

]